import {NgModule} from '@angular/core';
import {NativeScriptRouterModule} from 'nativescript-angular/router';
import * as tslib_1 from "tslib";
import {AutoGeneratedComponent} from './auto-generated/auto-generated.component';

export var routes = [
  {
    path: '',
    redirectTo: '/auto-generated',
    pathMatch: 'full',
  },
  {
    path: 'auto-generated',
    component: AutoGeneratedComponent,
  },
];
var AppRoutingModule = /** @class */ (function ()
  {
    function AppRoutingModule()
      {
      }

    AppRoutingModule = tslib_1.__decorate([
      NgModule({
        imports: [NativeScriptRouterModule.forRoot(routes)],
        exports: [NativeScriptRouterModule]
      })
    ], AppRoutingModule);
    return AppRoutingModule;
  }());
export {AppRoutingModule};
//# sourceMappingURL=app-routing.module.tns.js.map
